name: random-learning
version: git
summary: Random term and stackoverflow.com title for learning.
description: Random term and stackoverflow.com title for learning.
base: core18
grade: stable
confinement: strict

apps:
  random-learning:
    command: random-learning.js
    plugs: [ network ]

parts:
  random-learning:
    plugin: nodejs
    source: https://github.com/thehavays/random-learning.git
    nodejs-package-manager: npm
