name: random-learning
version: git
summary: Random term and stackoverflow.com title for learning.
description: Random term and stackoverflow.com title for learning.
base: core18
grade: stable
confinement: strict

apps:
  random-learning-cli:
    command: random-learning

parts:
  random-learning:
    plugin: nodejs
    #nodejs-version: 16.14.0
    nodejs-package-manager: npm
    source: https://github.com/thehavays/random-learning.git

plugs:
  random-learning-home:
    interface: home
  random-learning-network:
    interface: network
